name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-docker:
    uses: divkix/reusable-workflows/.github/workflows/docker-build-publish.yml@main
    with:
      repo_name: ${{ needs.get-repo-info.outputs.repo_name }}
    secrets: inherit

  automerge-dependabot-pr:
    if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'
    needs:
      - build-docker
    permissions:
      pull-requests: write
      contents: write
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
