name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  get-repo-info:
    uses: divkix/reusable-workflows/.github/workflows/get-repo-info.yml@main

  build-docker:
    needs: get-repo-info
    strategy:
      fail-fast: false
      matrix:
        include:
          - base-image: python:3.11-slim
            tag: py311
            latest_image: true
          - base-image: python:3.10-slim
            tag: py310
            latest_image: false
          - base-image: python:3.9-slim
            tag: py39
            latest_image: false

    uses: divkix/reusable-workflows/.github/workflows/docker-build-publish.yml@main
    with:
      repo_name: ${{ needs.get-repo-info.outputs.repo_name }}
      dockerfile: ./tools/docker/Dockerfile
      build_args: BASE_IMAGE=${{ matrix.base-image }}
      tag: ${{ matrix.tag }}
      latest_image: ${{ matrix.latest_image }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  automerge-dependabot-pr:
    needs: build-docker
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
