name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  get-repo-info:
    uses: divkix/reusable-workflows/.github/workflows/get-repo-info.yml@main

  build-docker:
    needs: get-repo-info
    uses: divkix/reusable-workflows/.github/workflows/docker-build-publish.yml@main
    with:
      repo_name: ${{ needs.get-repo-info.outputs.repo_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  automerge-dependabot-pr:
    needs: build-docker
    uses: divkix/reusable-workflows/.github/workflows/automerge-dependabot-pr.yml@main
